# Generated by Django 2.0 on 2017-12-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/pictures', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='информация о компании')),
                ('phone', models.CharField(max_length=256, verbose_name='телефон')),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='companyimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_blog.CompanyInformation'),
        ),
    ]
