# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_uk',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
