# Generated by Django 2.0 on 2017-12-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0002_auto_20171218_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='companyinformation',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компания'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
