# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0002_auto_20180126_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/pictures', verbose_name='banner')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_blog.CompanyInformation')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
