# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0003_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_revived',
            field=models.BooleanField(default=False),
        ),
    ]
