# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0004_auto_20171221_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='companyimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='companyinformation',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_blog.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(upload_to='company/pictures', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='about',
            field=models.TextField(verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='about_en',
            field=models.TextField(null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='address',
            field=models.CharField(max_length=256, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='address_en',
            field=models.CharField(max_length=256, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='address_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='blog/pictures', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_blog.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/pictures', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
    ]
