# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0005_auto_20180214_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='banner_title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='banner_title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='banner_title_uk',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
