# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0006_auto_20180110_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='title_image_1',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='title_image_2',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='title_image_3',
        ),
    ]
