# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 10:36
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0006_auto_20180214_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=256)),
                ('review', models.TextField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created'],
            },
        ),
    ]
