# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0007_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(verbose_name='review'),
        ),
    ]
