# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_blog', '0007_auto_20180111_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='phone',
            field=models.TextField(),
        ),
    ]
