# Generated by Django 2.0 on 2017-12-17 10:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lions_heart_products.Category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='collection/logos', verbose_name='логотип коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание коллекции')),
            ],
            options={
                'verbose_name_plural': 'Коллекции',
                'verbose_name': 'Коллекция',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products', verbose_name='изображение')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
                'verbose_name': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('title_image', models.ImageField(upload_to='catalog/products', verbose_name='титульное изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Мужская', 'Мужская'), ('Женская', 'Женская')], default='Женская', max_length=7, verbose_name='тип коллекции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Category', verbose_name='категория')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Collection', verbose_name='коллекция')),
                ('recommended_items', models.ManyToManyField(blank=True, related_name='_item_recommended_items_+', to='lions_heart_products.Item', verbose_name='рекомендованные товары')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['-created'],
                'verbose_name': 'Товар',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.TextField(verbose_name='характекристики товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item', verbose_name='товар')),
            ],
            options={
                'verbose_name_plural': 'Характекристики товара',
                'verbose_name': 'Характеристика товара',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item', verbose_name='товар'),
        ),
    ]
