# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0002_auto_20180128_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='size'),
        ),
    ]
