# Generated by Django 2.0 on 2017-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0002_specs_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='specs',
            field=models.TextField(blank=True, null=True, verbose_name='характекристики товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена'),
        ),
        migrations.DeleteModel(
            name='Specs',
        ),
    ]
