# Generated by Django 2.0 on 2017-12-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0003_auto_20171219_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
