# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0003_specs_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lions_heart_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='revived_present',
            field=models.BooleanField(default=True),
        ),
    ]
