# Generated by Django 2.0 on 2017-12-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0004_auto_20171219_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='диаметр')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='вес')),
                ('specs', models.TextField(blank=True, null=True, verbose_name='прочие характекристики')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item')),
            ],
            options={
                'verbose_name': 'Характекристика изделия',
                'verbose_name_plural': 'Характекристики изделия',
            },
        ),
    ]
