# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0004_auto_20180206_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_leather_bracelet',
            field=models.BooleanField(default=True),
        ),
    ]
