# Generated by Django 2.0 on 2017-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0005_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='specs',
            name='specs_en',
            field=models.TextField(blank=True, null=True, verbose_name='прочие характекристики'),
        ),
        migrations.AddField(
            model_name='specs',
            name='specs_ru',
            field=models.TextField(blank=True, null=True, verbose_name='прочие характекристики'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='длина, мм'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='вес, гр'),
        ),
    ]
