# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0005_item_is_leather_bracelet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_leather_bracelet',
            new_name='is_not_leather_chain',
        ),
    ]
