# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0006_auto_20171220_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Сollection', 'verbose_name_plural': 'Сollections'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='specs',
            options={'verbose_name': 'Specs', 'verbose_name_plural': 'Specs'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lions_heart_products.Category', verbose_name='parent сategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection/logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='catalog/products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Category', verbose_name='сategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Collection', verbose_name='сollection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recommended_items',
            field=models.ManyToManyField(blank=True, related_name='_item_recommended_items_+', to='lions_heart_products.Item', verbose_name='recommended'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_image',
            field=models.ImageField(upload_to='catalog/products', verbose_name='title image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Women', max_length=7, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='diameter, mm'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='length, mm'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='specs',
            field=models.TextField(blank=True, null=True, verbose_name='other specs'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='specs_en',
            field=models.TextField(blank=True, null=True, verbose_name='other specs'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='specs_ru',
            field=models.TextField(blank=True, null=True, verbose_name='other specs'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight, gr'),
        ),
    ]
