# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0006_auto_20180208_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_gift',
        ),
        migrations.AddField(
            model_name='item',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='sales price'),
        ),
    ]
