# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0007_auto_20180209_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price')),
                ('sales', models.IntegerField(blank=True, null=True, verbose_name='sales')),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='sales price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
