# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0008_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AddField(
            model_name='attributes',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight, gr'),
        ),
    ]
