# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0009_auto_20180209_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sales_price',
        ),
    ]
