# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0010_auto_20180213_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='diameter, mm'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height, mm'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='length, mm'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='specs',
            field=models.TextField(blank=True, null=True, verbose_name='other specs'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='width, mm'),
        ),
    ]
