# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0010_auto_20180114_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
