# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0011_auto_20180213_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='specs',
        ),
    ]
