# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0012_remove_item_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sales',
            field=models.IntegerField(blank=True, null=True, verbose_name='sales'),
        ),
    ]
