# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0012_remove_attributes_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='height',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='length',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='size',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='width',
        ),
    ]
