# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0015_auto_20180216_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
