# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_products', '0017_item_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='length, cm'),
        ),
    ]
