# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lions_heart_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=256, verbose_name='name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('payment_type', models.CharField(choices=[('Credit card', 'Credit card'), ('Cash', 'Cash')], default='Credit Card', max_length=11, verbose_name='payment type')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='comment')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='total cost')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'abstract': False,
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_cart.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Item in order',
                'verbose_name_plural': 'Items in orders',
            },
        ),
    ]
