# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lions_heart_products', '0006_auto_20171220_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=256, verbose_name='имя покупателя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=13, verbose_name='телефон')),
                ('payment_type', models.CharField(choices=[('Карта', 'Карта'), ('Наличные', 'Наличные')], default='Карта', max_length=8, verbose_name='способ платежа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='общая_стоимость')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Заказы',
                'abstract': False,
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_products.Item', verbose_name='товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_heart_cart.Order', verbose_name='заказ')),
            ],
            options={
                'verbose_name_plural': 'Товары в заказе',
                'verbose_name': 'Товар в заказе',
            },
        ),
    ]
