# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 19:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_cart', '0002_auto_20180205_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380441234567'. Up to 12 digits allowed.", regex='^\\+?\\d{9,12}$')], verbose_name='phone*'),
        ),
    ]
