# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_cart', '0003_auto_20180205_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Credit card', 'Credit card'), ('Cash', 'Cash')], default='Credit Card', max_length=15, verbose_name='payment type'),
        ),
    ]
