# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_cart', '0004_auto_20180207_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
