# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_cart', '0005_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name'),
        ),
    ]
