# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_heart_cart', '0006_auto_20180321_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail*'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Credit card', 'Credit card'), ('Cash', 'Cash')], default='Credit Card', max_length=15, null=True, verbose_name='payment type'),
        ),
    ]
